name: Main workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - github-actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.13
      - name: Install libraries
        run: |
            ls
            python -m pip install --upgrade pip
            pip install pipenv
            pipenv install
            # if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: pytest-check
        run: |
            pytest
